language: node_js

node_js:
   - lts/*

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
   - npm install -g --silent @angular/cli

script:
   - ng build --prod

after_success:
  - firebase deploy -P default --only hosting --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build

notifications:
  email:
    on_failure: change
    on_success: change
